In [1]:
import pandas as pd

In [32]:
df2 = pd.read_csv("raw_data.csv")

In [6]:
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [7]:
df2.isnull().sum()

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [8]:
df4 = pd.read_csv("raw_data.csv")

In [9]:
df4

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [10]:
cleaned_data = df4.copy()
cleaned_data.fillna(0, inplace=True)

In [11]:
cleaned_data.drop_duplicates(inplace=True)

In [12]:
cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [13]:
cleaned_data.fillna(0, inplace=True)

In [14]:
cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [15]:
age_mean = cleaned_data["age"].mean()
cleaned_data["age"].fillna(age_mean, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\2006395804.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["age"].fillna(age_mean, inplace=True)

In [16]:
cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [17]:
income_mean = cleaned_data["income"].mean()
cleaned_data["income"].fillna(income_mean)

0     55000.0
2     62000.0
3     47000.0
4         0.0
5     51000.0
6     73000.0
7     68000.0
8     62000.0
9     45000.0
10    58000.0
Name: income, dtype: float64

In [18]:
cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [19]:
cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [20]:
cleaned_data["name"].replace(0, "Unknown", inplace=True)
cleaned_data["name"].fillna("Unknown", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\2552844909.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["name"].replace(0, "Unknown", inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\2552844909.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["name"].fillna("Unknown", inplace=True)

In [21]:
cleaned_data

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6       Unknown  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [22]:
cleaned_data["country"].replace(0, "Unknown", inplace=True)
cleaned_data["country"].fillna("Unknown", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\166376753.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["country"].replace(0, "Unknown", inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\166376753.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["country"].fillna("Unknown", inplace=True)

In [23]:
cleaned_data["gender"].replace(0, "Unknown", inplace=True)
cleaned_data["gender"].fillna("Unknown", inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\2618850330.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["gender"].replace(0, "Unknown", inplace=True)
C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\2618850330.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["gender"].fillna("Unknown", inplace=True)

In [24]:
cleaned_data

    id          name   age  country   gender   income
0    1      John Doe  29.0      USA     Male  55000.0
2    2    Jane Smith   0.0   Canada   Female  62000.0
3    3          Alex   0.0      USA  Unknown  47000.0
4    4  Maria Garcia  34.0    Spain   Female      0.0
5    5        Li Wei  27.0    China     Male  51000.0
6    6       Unknown  45.0    India   Female  73000.0
7    7    Ahmed Khan  38.0  Unknown     Male  68000.0
8    8    Rachel Lee  29.0      USA   Female  62000.0
9    9   Carlos Ruiz   0.0   Mexico     Male  45000.0
10  10   Emily Davis  31.0      USA  Unknown  58000.0

In [25]:
mean_income = cleaned_data[cleaned_data["income"] != 0]["income"].mean()
cleaned_data["income"].replace(0, mean_income, inplace=True)

C:\Users\Admin\AppData\Local\Temp\ipykernel_19136\3727219539.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cleaned_data["income"].replace(0, mean_income, inplace=True)

In [26]:
cleaned_data

    id          name   age  country   gender        income
0    1      John Doe  29.0      USA     Male  55000.000000
2    2    Jane Smith   0.0   Canada   Female  62000.000000
3    3          Alex   0.0      USA  Unknown  47000.000000
4    4  Maria Garcia  34.0    Spain   Female  57888.888889
5    5        Li Wei  27.0    China     Male  51000.000000
6    6       Unknown  45.0    India   Female  73000.000000
7    7    Ahmed Khan  38.0  Unknown     Male  68000.000000
8    8    Rachel Lee  29.0      USA   Female  62000.000000
9    9   Carlos Ruiz   0.0   Mexico     Male  45000.000000
10  10   Emily Davis  31.0      USA  Unknown  58000.000000

In [27]:
cleaned_data.isnull().sum()

id         0
name       0
age        0
country    0
gender     0
income     0
dtype: int64

In [28]:
cleaned_data.describe()

             id        age        income
count  10.00000  10.000000     10.000000
mean    5.50000  23.300000  57888.888889
std     3.02765  16.892141   8849.914556
min     1.00000   0.000000  45000.000000
25%     3.25000   6.750000  52000.000000
50%     5.50000  29.000000  57944.444444
75%     7.75000  33.250000  62000.000000
max    10.00000  45.000000  73000.000000

In [142]:
cleaned_data.to_csv("cleaned_dataset.csv", index=False)